### ISSUE TITLE
Adding Break Points on Product On Suggested Order Screen

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#10]
When viewing the data presented on the Product on Suggested Order Screen (Product Details), there is a lot of data presented, without well defined breaks for the eyes to stop at.

As discussed today, changing the color of the spaces between section, provides a break point for the eyes, and is easier to train myself precisely where I need to look on the screen, when quickly glancing for a specific piece of information.

URL: http://10.5.49.15:8051/orders/details?OWNORDER=1&PQ_LOCN=1&PQ_SUPL=015025&PQ_SUPLSUB=&PQ_SOQSEQNUM=1&PQ_PROD=161836&PRODPROP=SQ
![image](https://cloud.githubusercontent.com/assets/22618097/19277869/3a8adfa8-8fa9-11e6-950e-93d03520d3d5.png)

**Comment by kingharrison** [comment]
<img width="1291" alt="screen shot 2016-10-11 at 3 06 16 pm" src="https://cloud.githubusercontent.com/assets/6114928/19284539/496e80c2-8fc4-11e6-88ba-0fff7f510dba.png">

Added. I tried to go subtle but effective. Let me know if they are too subtle.

**Comment by ajschenk** [comment]
It doesn't look like I've received this update yet; however, looking at the screen shot, I think that slightly darker may be better.

**Comment by kingharrison** [comment]
I think you will need to hold down SHIFT and hit refresh. It is caching the CSS (the style files for speed).

**Comment by ajschenk** [comment]
That worked. Thank you.

[CBWblueBevelLogo]

Drew Schenk
Vice President of Purchasing
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 146
800-992-0592   Fax: 717-285-8008
Drew.Schenk@cooperbooth.com<mailto:Drew.Schenk@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com>

**Comment by kingharrison** [comment]
For color changes give this one a little bit of navigating to see and I can definitely go darker, but see if this makes a difference.

**Comment by kingharrison** [comment]
@ajschenk does the color work or need to be darker?

**Comment by ajschenk** [comment]
I think that color will work.

[CBWblueBevelLogo]

Drew Schenk
Vice President of Purchasing
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 146
800-992-0592   Fax: 717-285-8008
Drew.Schenk@cooperbooth.com<mailto:Drew.Schenk@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com>

**Comment by kingharrison** [comment]
Great! I will close this. 

-King Harrison
Sent from iPhone
Please excuse all typos




On Thu, Oct 13, 2016 at 6:00 PM -0400, "ajschenk" <notifications@github.com> wrote:










I think that color will work.





[CBWblueBevelLogo]





Drew Schenk


Vice President of Purchasing


200 Lincoln West Drive


Mountville, PA 17554


717-285-8000 ext. 146


800-992-0592   Fax: 717-285-8008


Drew.Schenk@cooperbooth.com<mailto:Drew.Schenk@cooperbooth.com>


www.cooperbooth.com<http://www.cooperbooth.com>
