### ISSUE TITLE
Bug: Search K3S

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#11]
When searching for an item (it has been any item that I've tried), using the search feature from Today's Agenda, I receive the following error:

URL: http://10.5.49.15:8051/search/productresults?selectid=id&searchtext=467852

![image](https://cloud.githubusercontent.com/assets/22618097/19282371/2136c4e6-8fbc-11e6-860a-5d15063ebb32.png)

![image](https://cloud.githubusercontent.com/assets/22618097/19282388/3aba1d3c-8fbc-11e6-99da-33ce8c3208f5.png)

**Comment by kingharrison** [comment]
For Product IDs this is now fixed. Product Description, Supplier ID, and PO search is still being worked on.

**Comment by kingharrison** [comment]
Added supplier search. 

Besides POs what else would you like to search?

**Comment by ajschenk** [comment]
It would be great to search by suppliers item number, which is currently in the "your space" section shown below, as well as the Manufacturer ID field in the Product Details. 

![image](https://cloud.githubusercontent.com/assets/22618097/19439760/54a3b222-944d-11e6-93f3-988fe2969619.png)

![image](https://cloud.githubusercontent.com/assets/22618097/19439845/a61c7a08-944d-11e6-9863-7ddecb39c383.png)

**Comment by kingharrison** [comment]
Added to 10.17.16.
