### ISSUE TITLE
Identify seasonal profile factors on Products on Suggested Order Screen

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#12]
When looking at the Products on Suggested Order Screen, it is not evident whether or not the item has a seasonal profile applied. 

In Jellybean, I could quickly glance at the "Factor" section, as shown below, and make a judgement as to whether or not we are on track, with reviewing prior periods and 21 day demand history.

![image](https://cloud.githubusercontent.com/assets/22618097/19387685/d6c8627c-91e9-11e6-8128-4d5ce68302f3.png)

If this could be fit into the demand section in Blackbean, I think a lot of people would find it useful. Simply knowing that there is a seasonal profile at a glance answers a lot of questions as to why the set average looks so far off from demand.

![image](https://cloud.githubusercontent.com/assets/22618097/19387719/0493ea82-91ea-11e6-9333-7b6a7ab1daac.png)

**Comment by kingharrison** [comment]
Added and should be available Monday.
