### ISSUE TITLE
Blackbean Demand not matching Jellybean

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#13]
I've found an item where Blackbean is not showing any demand history in the Last 21 day section; however, Jellybean is reflecting the demand accurately. 

![image](https://cloud.githubusercontent.com/assets/22618097/19388140/0e94234c-91ec-11e6-907c-b7c1058f088a.png)

![image](https://cloud.githubusercontent.com/assets/22618097/19388159/2ca5ef3c-91ec-11e6-93d9-81acd739574c.png)
URL: http://10.5.49.15:8051/orders/details?OWNORDER=1&PQ_LOCN=1&PQ_SUPL=151469&PQ_SUPLSUB=LC&PQ_SOQSEQNUM=1&PQ_PROD=208116&PRODPROP=SQ

History is displayed appropriately in the sales journal. 
![image](https://cloud.githubusercontent.com/assets/22618097/19388192/4c3ba99a-91ec-11e6-8be4-bfd3d11d907f.png)

**Comment by kingharrison** [comment]
Let me work on this one.

**Comment by kingharrison** [comment]
Please check this one out Drew. This looks good now.
