### ISSUE TITLE
Clearing Suggested Quantity of Multiple Items

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#14]
If I'm at a point, where I'd like to clear the suggested quantity of multiple items (to zero), is there a way to do that without individually changing the quantity for each item? In JB, I would enter a "4" in the block next to each item to be cleared. With BB, I'm not sure what all of the purposes are for the check boxes at each line item.

![image](https://cloud.githubusercontent.com/assets/22618097/19388417/7b99f006-91ed-11e6-816d-94e707cf01fe.png)

**Comment by kingharrison** [comment]
Ohhhh, let me work on that. Good idea.

**Comment by kingharrison** [comment]
This has been added to version 10.15.16. Should see soon.
