### ISSUE TITLE
Order Cycle Analysis

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#15]
When trying to approve a new order cycle, by clicking "35" as depicted below, followed by the "check mark," I receive an error message stating "Supplier ID does not exist. This has occurred on all vendors that I have tried to update today.

URL: http://10.5.49.15:8051/suppliers/ordercycle?LOCN=1&SUPL=012145&SUPLSUB=

![image](https://cloud.githubusercontent.com/assets/22618097/19448061/203db2be-946e-11e6-97aa-59cef5d964ca.png)

**Comment by kingharrison** [comment]
Just tested on a supplier as well and was able to confirm this. This is a weird one. It isn't happening on our test system but is obviously happening on yours. I might end up calling you if we need help pinpointing this one.

**Comment by kingharrison** [comment]
Will you give this a try? I think this is now fixed.

**Comment by kingharrison** [comment]
Hi Drew, wanted to check in on this. Is this working to your specifications now?

**Comment by ajschenk** [comment]
This is now working perfectly. I have updated the order cycle on all of my vendors with a OC over 6 months.

**Comment by kingharrison** [comment]
Fantastic! I will close.
