### ISSUE TITLE
Product Maintenance Display

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#16]
When viewing a list of products, in this case, new products, I would like the "Product Maintenance" button to take me directly to that item's PM screen. Currently, when clicking on PM, it opens a new window, Product Settings, which is unfiltered and showing all products. For time savings, going directly to the item I clicked on would be helpful.

URL: http://10.5.49.15:8051/orders/products?PQ_LOCN=1&PQ_SUPL=013130&PQ_SUPLSUB=REG&PQ_SOQSEQNUM=1&PRODPROP=NW&OWNORDER=0

![image](https://cloud.githubusercontent.com/assets/22618097/19767812/9779dd24-9c22-11e6-9ca2-ef1eb69e0cdb.png)

![image](https://cloud.githubusercontent.com/assets/22618097/19767824/a2321560-9c22-11e6-9fad-85e21b3c8849.png)

**Comment by kingharrison** [comment]
Adjusted in version 10.27.16 

For a more conventional naming scheme Product Maintenance is being replaced by Product Settings. However the button now takes you to the desired screen. You should see the adjustment tomorrow.
