### ISSUE TITLE
Start List Error

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#17]
When clicking "Start List" from this URL (http://10.5.49.15:8051/orders/products?PQ_LOCN=1&PQ_SUPL=015025&PQ_SUPLSUB=&PQ_SOQSEQNUM=1&PRODPROP=SQ&OWNORDER=0), I am taken to a page with the following error.

![image](https://cloud.githubusercontent.com/assets/22618097/20268617/ee518136-aa4d-11e6-9aaf-8fb32a47ceb1.png)

URL of error page: http://10.5.49.15:8051/orders/details?STARTLIST=1&PQ_LOCN=1&PQ_SUPL=015025&PQ_SUPLSUB=&PQ_SOQSEQNUM=1&PRODPROP=SQ&OWNORDER=0&ORDERBY=SI

**Comment by kingharrison** [comment]
On it Drew. Let me look.

**Comment by kingharrison** [comment]
Should be fixed now.
