### ISSUE TITLE
Approved Order Screen

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#18]
The "Approved Order Screen" in JB is set to sort the orders with the most recently accepted PO on the top. This is beneficial for my Purchasing Assistants, as they use this list to verify that all orders have dropped to AFS, and at times, use this as a reference for the PO#. Below is a screen shot of the JB screen:

![image](https://cloud.githubusercontent.com/assets/22618097/20448239/0aca9256-adb1-11e6-81e7-efd8f07c1ea2.png)

![image](https://cloud.githubusercontent.com/assets/22618097/20448148/9fe6cd6a-adb0-11e6-8ff1-e79ed5b23160.png)

BB is giving several sorting options, but I cannot find a way to display in order of approval time.

![image](https://cloud.githubusercontent.com/assets/22618097/20448293/425d3016-adb1-11e6-996d-37136afb8c36.png)

**Comment by kingharrison** [comment]
So this screen already exists! I will work on where to put a button for this one, but it is a menu option on the left. 

<img width="279" alt="screen shot 2016-11-19 at 7 08 13 am" src="https://cloud.githubusercontent.com/assets/6114928/20455313/0faf43a4-ae27-11e6-9306-b1b753b5bb93.png">


Now do you have a good suggestion on where to put the option or the button? I could have a button near options to filter down POs to the vendor that is showing.

**Comment by kingharrison** [comment]
I also realize I haven't highlighted this enough. There are extra options on every screen. The are in the upper left hand corner and when you click on the downward facing carrot they show up. There aren't extra options everywhere, but if they exist this is where I put them. 

<img width="892" alt="screen shot 2016-11-19 at 7 14 21 am" src="https://cloud.githubusercontent.com/assets/6114928/20455354/d6dd65be-ae27-11e6-991d-3dccb8c9675a.png">
