### ISSUE TITLE
Sales Journal Order vs. Ship Qty Incorrect

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#19]
When comparing the Sales Journal on JB vs. BB, the information displayed in BB is not accurate. BB is showing the "Order Quantity" as 0, and "Ship Quantity" as "X" numeric value. It appears that these two columns are backwards, as we currently have demand, and zero product to fill the order. Below is a screen shot from both systems.

URL:http://10.5.49.15:8051/orders/salesjournal?IE_LOCN=1&IE_SUPL=155987&IE_SUPLSUB=&IE_PROD=776187
![image](https://cloud.githubusercontent.com/assets/22618097/20632750/abd75a24-b30d-11e6-8a20-769a1c993880.png)

![image](https://cloud.githubusercontent.com/assets/22618097/20632753/b5f4ec60-b30d-11e6-94f0-0cd78182e694.png)

**Comment by kingharrison** [comment]
I want to confirm with you but I believe the Order Quantity and Ship Quantity fields are fixed, as well as the Customer Number (and fixed how the Customer Number, Name, and Chain Number fields are aligned). 

Accumulated demand does not work at the moment very well. I am working on that.
