### ISSUE TITLE
Order Not Approved

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#21]
When trying to approve orders in BB this morning, I receive an "order not approved" message in the upper right hand corner (red pop-up). I'm approving order in JB at the point.

**Comment by kingharrison** [comment]
Got Drew. We are working on it.

**Comment by kingharrison** [comment]
Drew
@UserInHIsName @yeltnarb have created a fix and it should be over on the machine. When you are ready you can test and lest us know if you had success or not.

**Comment by ajschenk** [comment]
Still having the same issue this morning.

URL: http://10.5.49.15:8051/orders/approve?LOCN=1&SUPL=156680&SUPLSUB=&BUYR=03&SOQSEQNUM=1

![image](https://cloud.githubusercontent.com/assets/22618097/21142510/8a77060c-c110-11e6-9a37-2fe28d34ef3a.png)

**Comment by kingharrison** [comment]
Drew, we finished it test environment and we're able to test a few APIs that we're fixed. You should be able to approve orders today through Black Bean with no problem.

**Comment by ajschenk** [comment]
Thanks, King. I will try some orders in BB tomorrow morning.

[CBWblueBevelLogo]

Drew Schenk
Vice President of Purchasing
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 146
800-992-0592   Fax: 717-285-8008
Drew.Schenk@cooperbooth.com<mailto:Drew.Schenk@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com>

**Comment by ajschenk** [comment]
Order approval worked this morning, and transferred to AFS as expected. Thanks.

**Comment by kingharrison** [comment]
Hooray! @UserInHIsName @yeltnarb
