### ISSUE TITLE
Highlighted roll over

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#23]
When you roll over an item like below it highlights, which leads one to believe you can click on and open it.  

Click on the item description or on right clicking as in K3S would be nice.

![image](https://cloud.githubusercontent.com/assets/24811949/21568560/9ca75a4a-ce83-11e6-8f01-6d65801fff18.png)

**Comment by kingharrison** [comment]
@tnrn9b this is the particular ability I was describing.

**Comment by tnrn9b** [comment]
This is going to be a bit delicate to implement a global solution. I'll need a bit to rethink what I was planning to do here.

**Comment by kingharrison** [comment]
@michaelh18 this is actively being worked on, btw. Might have this for testing in a week.

**Comment by kingharrison** [comment]
Hoping to have this out to you and working before Friday @michaelh18

**Comment by kingharrison** [comment]
This is added!

in User settings go and turn on Clickline. 

When you click on the row the first button in options will be what is pressed EXCEPT when that option is delete. If you find one not working to this let me know.
