### ISSUE TITLE
Fixed cycle

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#24]
When you attempt to change the fixed cycle settings, the popup window opens with defaults instead of what the current settings are.  Since there is a remove settings button, I believe the fields should be populated with the current settings.

![image](https://cloud.githubusercontent.com/assets/24811949/22887738/2db643aa-f1d1-11e6-9ef5-9c01b4f088f0.png)

![image](https://cloud.githubusercontent.com/assets/24811949/22887747/377b4840-f1d1-11e6-8602-cf684ca12644.png)

**Comment by kingharrison** [comment]
Fantastic idea! Just fixed it and added. Will be in the new version update of 2.13.17 (you can see the current version in the bottom right hand corner).

**Comment by kingharrison** [comment]
This has been done and updated on the version you are on.
