### ISSUE TITLE
Start List

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#25]
While on the Products on Suggested Order Screen, if you open an item detail and then go back to Products on Suggested Order Screen and hit Start List, the list will begin with the item you opened.  Clicking on Start List won't begin with first item on the list until you click open the detail screen for the first item on the list.

**Comment by kingharrison** [comment]
Can you elaborate a bit more?
Also on each line the last button is to do the start list from that point on. Does that help?

-King Harrison
Sent from iPhone
Please excuse all typos




On Wed, Feb 15, 2017 at 9:50 AM -0500, "michaelh18" <notifications@github.com> wrote:












While on the Products on Suggested Order Screen, if you open an item detail and then go back to Products on Suggested Order Screen and hit Start List, the list will begin with the item you opened.  Clicking on Start List won't begin with first item on the list until you click open the detail screen for the first item on the list.

**Comment by kingharrison** [comment]
@michaelh18 we had an email conversation outside of this. Do you feel this issue was addressed or do you think we need to take a further look together?
