### ISSUE TITLE
Convenience Pack Threshold

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#26]
In Jelly Bean, the Convenience Pack Threshold can be set as low as 10%.  In Black Bean you can only set it as low as 30%.  10% is more desirable. 

![image](https://cloud.githubusercontent.com/assets/24811949/23414898/7cea5606-fdab-11e6-92a8-ba67bc766706.png)

![image](https://cloud.githubusercontent.com/assets/24811949/23414888/7354c1ee-fdab-11e6-930e-24ab8a150ff8.png)

![image](https://cloud.githubusercontent.com/assets/24811949/23414915/8b81e9ea-fdab-11e6-9682-bb3b84bb8e37.png)
 
![image](https://cloud.githubusercontent.com/assets/24811949/23414940/a3d0bfe4-fdab-11e6-84e0-8ae68c32ada8.png)

**Comment by kingharrison** [comment]
Let me research that. They should match.

**Comment by kingharrison** [comment]
Hey @michaelh18 this should be fixed now and have the proper error message if you go below 10.

**Comment by michaelh18** [comment]
Looks good.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>
