### ISSUE TITLE
Product Settings Start List

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#28]
From here

![image](https://cloud.githubusercontent.com/assets/24811949/24805742/d39e33c6-1b80-11e7-9a71-253d12a4f181.png)

Click on Product Settings
![image](https://cloud.githubusercontent.com/assets/24811949/24805767/e05a3c2c-1b80-11e7-9b8e-ec0e049b8a34.png)

Then click on Start to start the list of product settings and get this:
![image](https://cloud.githubusercontent.com/assets/24811949/24805851/f837b662-1b80-11e7-85eb-04828a4aa245.png)

Which I believe is for US Smokeless

**Comment by kingharrison** [comment]
Thanks Mike. 

Honestly that button is just a shell and doesn't have the code behind it yet. I will address it this weekend and try and get it up for you soon.

**Comment by michaelh18** [comment]
Any idea when we will be able to see Royal Farms history split out like it is in Jelly Bean.  It is something that Michele and I use frequently.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Do you mean where it shows the multiple levels of history? I have another developer who is working on BB with me. I can actually start that piece with him next week.

**Comment by michaelh18** [comment]
Yes, that is it.  Great.  It’s a fantastic tool for us and really speeds up a couple different tasks.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Hey @michaelh18 

Product settings start list and multiple history is now up on your setup. closing this issue but let me know if you have any questions.
