### ISSUE TITLE
All Location Item lookup items view status only

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#29]
Need to be able to adjust items after having looked them up with All Location.  Currently they come up as view only.

![image](https://cloud.githubusercontent.com/assets/24811949/25483832/792fe420-2b25-11e7-8ed6-002620c21d3d.png)

![image](https://cloud.githubusercontent.com/assets/24811949/25483835/7ef0edf0-2b25-11e7-89de-af433ad7821a.png)

**Comment by kingharrison** [comment]
Ok I can have a button show up if the order is currently locked. If not, you can take over the order. That work?

-King Harrison
Sent from iPhone
Please excuse all typos
________________________________

**Comment by michaelh18** [comment]
The order isn’t locked.  It’s every item, every time.  I am able to hop into Jelly Bean and change it there without any issues.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Just double checking: you mean adjusting the average and order amounts correct?

It's actually a weakness in Jelly bean because you could edit someone else's order they have locked.

-King Harrison
Sent from iPhone
Please excuse all typos
________________________________

**Comment by michaelh18** [comment]
Yes.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Ok found a solution and this should now work, I think, to your liking. 

Check it out!
