### ISSUE TITLE
Old Order Cycles

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#30]
When updating Old Order Cycles the first vendor will not clear even after you update the order cycle.  

![image](https://cloud.githubusercontent.com/assets/24811949/25621015/23bb280e-2f1e-11e7-9c25-0415ce991047.png)

It says here that it it still 6 days even though if you enter into the vendor, it says 12 days.

![image](https://cloud.githubusercontent.com/assets/24811949/25621066/41b1d20e-2f1e-11e7-81cf-ff1d0097e334.png)
![image](https://cloud.githubusercontent.com/assets/24811949/25621088/4d1d235a-2f1e-11e7-9289-49ab80848fba.png)

**Comment by kingharrison** [comment]
Ok, good find. I am going to research. Thank ya sir!

**Comment by kingharrison** [comment]
Figured it out! It is because you approved an order then went to go handle the old order cycle. I will try and come up with a better way to display, but you did correctly work through the order. 

It is kinda one of those fringe cases.

**Comment by kingharrison** [comment]
Ok, so I have a solution and it isn't perfect, but I think it will avoid confusion on the user end. 

Basically we build those Agenda lists off the suggested orders. Once you approved the order it is hard for us to go back and 'un-approve' the order just to update the Order Cycle correctly. We end up in a situation where we need to choose a better option. So now once you approve an order that has an Old Order cycle it will just knock off your list for that day. The next day it would show back up and you would most likely take care of it then. 

Simple answer: you wont find yourself in a situation where a old order cycle is hanging out and not getting updated.

**Comment by michaelh18** [comment]
Sounds good to me.

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>
