### ISSUE TITLE
Copy History functions do not work

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#31]
Copy History ->Add to Existing History doesn't add the average correctly
Copy History ->Copy and Replace History doesn't work at all, only adds a couple periods and puts then in place prior years.

This shows the result Add to Existing History from Black Bean
![image](https://user-images.githubusercontent.com/24811949/26979218-0ace4b36-4cfc-11e7-8051-2e84e38f9ef3.png)

This shows the correct Add to Existing History, performed in Jelly Bean
![image](https://user-images.githubusercontent.com/24811949/26979273-3b20d222-4cfc-11e7-9230-ea4c6c46e179.png)

**Comment by kingharrison** [comment]
Appreciate the heads up. We will get on that now.

**Comment by kingharrison** [comment]
@michaelh18 

I was able to confirm the average when add to existing happens is not correct. Will work on that. 

However Copy and Replace as well as the historical periods before and after look correct on my end. 

Could you help me step by step with these identify the inconsistency?

**Comment by michaelh18** [comment]
King,

Here is another example.

[cid:image001.png@01D2E522.C9959D40]


Here is the correct one after I updated in Jelly Bean.

[cid:image004.png@01D2E523.4A917B30]
[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>

**Comment by kingharrison** [comment]
Finally found the bug in this one. Fix should be in Monday!
