### ISSUE TITLE
New Order Indentifier not displaying correctly

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#33]
This new feature is showing up in Status and in Total Adjustments.

![image](https://user-images.githubusercontent.com/24811949/30070841-b96a1852-9232-11e7-942e-c8b9257e7e27.png)

**Comment by kingharrison** [comment]
Hi Michael, can you help point out what you mean?

**Comment by kingharrison** [comment]
@michaelh18 I am going to close this as we had an offline to this github issue discussion and believe we are on the same page as it is working as expected.
