### ISSUE TITLE
Change Product Source

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#34]
Gives an error when trying to move and item to a subvendor.  I wasn't told this was working yet so the whole change product source may not be functional yet.

![image](https://user-images.githubusercontent.com/24811949/30558251-ca29d17c-9c7e-11e7-835a-04ee2eaacad2.png)

**Comment by kingharrison** [comment]
This is one currently being worked on. @tnrn9b do you see what would have triggered that?
