### ISSUE TITLE
Product Link Doesn't have Parent/Child

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#35]
Need to have the option in Product Link for Parent/Child like there is in Jelly Bean.

![image](https://user-images.githubusercontent.com/24811949/30558711-6831351c-9c80-11e7-83cd-1a007101c4b0.png)

![image](https://user-images.githubusercontent.com/24811949/30558749-8d2f8044-9c80-11e7-8f83-e6a266d251eb.png)

**Comment by kingharrison** [comment]
@tnrn9b this one as well

**Comment by tnrn9b** [comment]
Hi @michaelh18, 
Sorry it took me so long to respond to this. This is fixed. It should be available for you next week at the latest. Until then, use the 'X' type for the 'Parent/Child' record you're wanting to create.
