### ISSUE TITLE
Add Supplier

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#36]
Attempting to add a subvendor and get the message below "Entry must not be blank".  I have no idea which entry and it looks like i filled everything out that I needed to.

![image](https://user-images.githubusercontent.com/24811949/30608935-ea51edd0-9d47-11e7-8bb3-69c8e3cb4379.png)

**Comment by michaelh18** [comment]
Sorry, I missed the error with my screen shot.

![image](https://user-images.githubusercontent.com/24811949/30608987-12d20ef2-9d48-11e7-9f15-224963868dab.png)

**Comment by kingharrison** [comment]
Found the issue. You just need to add a Unit 6 Text to the box (Normally it is listed as 'Other...'). 

For some reason the defaults program didn't load it in there. I will work on fixing the defaults but once you put in Unit 6 text it should add. You can also change the Unit 6 text later if you want.
