### ISSUE TITLE
Hold Outs

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#38]
I am getting an error message when attempting to create a hold out.  I did not have any issues last week.

![image](https://user-images.githubusercontent.com/24811949/36393338-1d854a82-157d-11e8-8d28-7243c731daab.png)

**Comment by kingharrison** [comment]
Thanks @michaelh18 

@tnrn9b we should be able to test this on Dev box.

**Comment by kingharrison** [comment]
@michaelh18 put out a hotfix. See if that fixes it for you.

**Comment by michaelh18** [comment]
That appears to have worked.

Thanks,

[CBWblueBevelLogo]

Mike Hoffert
Category Manager
200 Lincoln West Drive
Mountville, PA 17554
717-285-8000 ext. 193
800-992-0592   Fax: 717-285-8008
Michael.Hoffert@cooperbooth.com<mailto:Michael.Hoffert@cooperbooth.com>
www.cooperbooth.com<http://www.cooperbooth.com/>
