### ISSUE TITLE
Product Link not working

### ISSUE THREAD

**Issue by michaelh18** [K3S/K3S-Replenish-Public#39]
I get the that they supplier doesn't exist when I try to link to or from an item.

![image](https://user-images.githubusercontent.com/24811949/37156296-b263c172-22b3-11e8-830b-1e8b0d44bc6d.png)

**Comment by kingharrison** [comment]
Hey @michaelh18 

Sorry It took me a second to respond. I am actually out of the office on vacation with the fam. 

@tnrn9b can you look at his values and see why the link might not be working?

**Comment by kingharrison** [comment]
@michaelh18 as an update we have identified the issue and are working on it. We are also adding some new abilities to this. Will let you know when it is fixed.

**Comment by kingharrison** [comment]
@michaelh18 we made some changes, added a new ability to edit a link, and pushed out to your install this morning. Please test and let us know if that solved your challenge.

**Comment by kingharrison** [comment]
@michaelh18 I am going to close this issue as I believe it has been addressed. I will send a separate followup email as well.
