### ISSUE TITLE
SOQ Simulator

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#4]
In Jellybean, when entering the SOQ Simulator, there is an option to "Update SOQ." Through Blackbean, I have updated the "Units on Order" field, based upon cuts to the order received today, and was able to calculate the new suggested order of 440. With that said, I cannot click on "Update SOQ," I need to manually updated the OQ on the Products Detail page.

URL: http://10.5.49.15:8051/orders/details?page=3&STARTLIST=1&PQ_LOCN=1&PQ_SUPL=156546&PQ_SUPLSUB=&PQ_SOQSEQNUM=1&PRODPROP=AL&OWNORDER=1&ORDERBY=SI
![image](https://cloud.githubusercontent.com/assets/22618097/19191782/da89a11e-8c71-11e6-875a-eda57ab1a710.png)

**Comment by kingharrison** [comment]
Thanks @ajschenk. Ask and you shall recieve! Verison 10.7.16. Should be up soon. 

<img width="1382" alt="screen shot 2016-10-07 at 11 29 11 am" src="https://cloud.githubusercontent.com/assets/6114928/19195884/563e1128-8c81-11e6-9bd9-49d9558de260.png">
