### ISSUE TITLE
Updating User Status to Manual

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#5]
I cannot find a way to update an item's user status, in this case, to manual. I've looked on the product details page, as well as on the product history page. Can you point me in the right direction?

![image](https://cloud.githubusercontent.com/assets/22618097/19237855/da3b6de8-8ecc-11e6-914c-d4bf53bd4c03.png)

**Comment by kingharrison** [comment]
Im glad you asked this. It is possible on the Product Details screen. I had not added it back to the Product Settings screen. I will put that option back for you tomorrow.

**Comment by kingharrison** [comment]
You can now set products to Normal, Manual, or Watch on the Product Settings Screen and the Products On Order Details Screen. 

The ability to set to Frozen and Probation needs an adjustment to handle the date. Should have soon. 

I have updated you to the latest.
