### ISSUE TITLE
Missing: Weekly Avg in custom text box

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#6]
In Jellybean,  we see the weekly average ("13/4 Average" / 4) in the user defined text box on the product details page. This is very useful when comparing the forecast average to the past 21 days demand, without needing to do the calculation for each item. Below is a screen shot from both Jellybean and Blackbean. If possible, I'd like this to be added to Blackbean.

![image](https://cloud.githubusercontent.com/assets/22618097/19271266/e5d46432-8f91-11e6-8d72-49b04f04d277.png)

![image](https://cloud.githubusercontent.com/assets/22618097/19271277/f826295e-8f91-11e6-821b-f651ecc5807e.png)

**Comment by kingharrison** [comment]
@UserInHIsName it looks like DETYOUR might not be getting all the lines.

**Comment by UserInHIsName** [comment]
Hmmm;

Jellybean does not use APIs, meaning that we will have to see how they are geting the average value in CBW_5MOD/K3S_9940 or 9930. Right?

**Comment by kingharrison** [comment]
@ajschenk this should be fixed tomorrow on the update
