### ISSUE TITLE
Sales Journal Export

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#7]
I would like the option to export the Sales Journal to a .csv file. This is incredibly useful for execution against a product recall, or even in discussion with Sales in regards to who is currently buying a product, preparing for product discontinuation/conversions, etc.

If possible, the ability to select a start and end date would be most helpful, as it pertains to recalls. This can be filtered down from the .csv file if necessary; however, I'm not looking to export one "page" at a time (ie: 12 records at a time). 

![image](https://cloud.githubusercontent.com/assets/22618097/19277373/6fa4c818-8fa7-11e6-8130-21ee5d7fdcd3.png)

**Comment by kingharrison** [comment]
@ajschenk workingon this today. 

In the CSV do you need accumulated demand and a total? or is the other pieces just fine? Date, Order Number, Order Quantity, Ship, Customer #, Name, and Chain? Is that all you want from a CSV (with date filtering)

**Comment by ajschenk** [comment]
Accumulated demand is not an important factor for this. That could be easily added via a pivot table, etc., once exported. For the export option, what is the date range that it will export, or will that be user defined? I would most certainly want more than one "page" to be exported.

**Comment by kingharrison** [comment]
The entirety of the file but I will have to require some filter. Either required chain, prod... trying to think what else needed.

-King Harrison
Sent from iPhone
Please excuse all typos

________________________________

**Comment by ajschenk** [comment]
This would most likely be exported from a specific item record, so it should already be filtered down to that item number.

If this helps, one the most useful needs for this would be in the event of a product recall. The manufacturer will notify us of a specific product, in which we need to contact all customers who received the product within a specific date range. This export file makes it very easy for my Customer Service department to begin contacting the appropriate accounts, as well as meets the needs for documentation that I need to retain for FDA audits.

**Comment by kingharrison** [comment]
Ok. So always required product ID and the rest would be filters. I think I can have that out by tomorrow then for you to test.

-King Harrison
Sent from iPhone
Please excuse all typos

________________________________

**Comment by ajschenk** [comment]
Excellent!

**Comment by kingharrison** [comment]
Added back smarter and you should be good to go. I will close this suggestion. IF you have any issues feel free to open a new one on here.
