### ISSUE TITLE
Notes to be deleted from Today's Agenda

### ISSUE THREAD

**Issue by ajschenk** [K3S/K3S-Replenish-Public#9]
I currently have two notes displaying on my "Today's Agenda" page, indicating that there was a problem processing PO's in the past. These notes do not display in Jellybean, and I am unable to delete the notes from Blackbean.

URL: http://10.5.49.15:8051/todaysagenda

![image](https://cloud.githubusercontent.com/assets/22618097/19277669/7bc40a36-8fa8-11e6-821b-9f4491da4c67.png)

**Comment by kingharrison** [comment]
This should be taken care of now.
